region = "us-east-1"
msk_cluster_name = "my-kafka-cluster"
msk_version = "3.1.1"
security_group_ids = [ "my-security-group-id" ]
client_subnets = [ "my-subnets-id1","my-subnets-id2" ]
owner = "xyz@gmail.com"
project = "my-kafka-project"
number_of_broker_nodes = "2"
instance_type = "kafka.t3.small"
ebs_volume_size = "50"
